### ISSUE TITLE
 When v0.7 will be released?

### ISSUE THREAD

**Issue by icotd** [leodip/goiabada#13]
Hi, currently I'm using Zitadel but since Goiabada is minimalist I'm considering to use Goiabada but waiting for v0.7 to avoid breaking changes like admin console. When v0.7 will be released? It would be great if you could publish beta versions to see what it will look like. Thank you!

**Comment by leodip** [comment]
Hello @icotd. Thanks for your interest. I'm working hard on the 0.7 version which is going to be the release candidate, before the official v1 release. I have improved many things in the code (well, not so much in terms of features - the feature scope is the same, but the code/architecture has been refactored to a much better state). Test coverage is also higher, more bugs fixed, etc. 

I won't be able to work full-time on the project, but I estimate it will take around 3 to 4 weeks to release v0.7. I’m doing my best to push it out, and things are looking good so far. I'm optimistic. Thanks for your patience 🙂
