### ISSUE TITLE
Support PostgreSQL as a session store

### ISSUE THREAD

**Issue by srstsavage** [leodip/goiabada#2]
Hi! Are there any plans for supporting postgres as a session store database? Thank you.

**Comment by leodip** [comment]
@srstsavage Thanks for the suggestion, I'm going to try and add that support. 

Do you mean only for the session state, or for the main DB too?

**Comment by leodip** [comment]
@srstsavage support for postgres and microsoft sql server has been added in latest v1.1 release.

**Comment by srstsavage** [comment]
Awesome, thank you!
